name: Test and Build OpenSearch Notebooks Backend Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: '1.0.0-beta1'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal -Dbuild.version_qualifier=beta1 -Dbuild.snapshot=false

      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          ref: '1.0.0-beta1'
          repository: 'opensearch-project/common-utils'
          path: common-utils
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-beta1

      - name: Build with Gradle
        run: |
          cd opensearch-notebooks
          ./gradlew build -Dopensearch.version=1.0.0-beta1

      - name: Create Artifact Path
        run: |
          mkdir -p opensearch-notebooks-builds
          cp -r ./opensearch-notebooks/build/distributions/*.zip opensearch-notebooks-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-notebooks
          path: opensearch-notebooks-builds
