name: Test and Build OpenSearch Notebooks Backend Plugin

on: [push, pull_request]

env:
  OPENSEARCH_VERSION: '1.1.0-SNAPSHOT'
  OPENSEARCH_BRANCH: '1.1'
  COMMON_UTILS_BRANCH: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: ${{ env.OPENSEARCH_BRANCH }}
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal

      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/common-utils'
          path: common-utils
          ref: ${{ env.COMMON_UTILS_BRANCH }}
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Build with Gradle
        run: |
          cd opensearch-notebooks
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Create Artifact Path
        run: |
          mkdir -p opensearch-notebooks-builds
          cp -r ./opensearch-notebooks/build/distributions/*.zip opensearch-notebooks-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-notebooks
          path: opensearch-notebooks-builds
