name: Release OpenSearch Notebooks Backend Plugin Artifacts
# This workflow is triggered on creating tags to main or an opensearch release branch
on:
  push:
    tags:
      - "v*"

env:
  PLUGIN_NAME: notebooksDashboards
  OPENSEARCH_VERSION: 1.x
  COMMON_UTILS_VERSION: main
  OPENSEARCH_PLUGIN_VERSION: 1.0.0.0-rc1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Run build
        run: |
          cd opensearch-notebooks
          ./gradlew build buildDeb buildRpm --no-daemon --refresh-dependencies -Dbuild.snapshot=false
          artifact=`ls ./build/distributions/*.zip`
          rpm_artifact=`ls ./build/distributions/*.rpm`
          deb_artifact=`ls ./build/distributions/*.deb`

          # aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/opendistro-notebooks/
          # aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-notebooks/
          # aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-notebooks/
          # aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"
